// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqFZN28asKdCCJ9nHLmo7y9-bksbLZGg',
    appId: '1:1036722190154:web:c2e8a3fa5060245da973b3',
    messagingSenderId: '1036722190154',
    projectId: 'sehatgah-e3a20',
    authDomain: 'sehatgah-e3a20.firebaseapp.com',
    storageBucket: 'sehatgah-e3a20.appspot.com',
    measurementId: 'G-GQ2DQMMJ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZ4ZmCw6chfGFCXboTwhIj936xPkaOPY',
    appId: '1:1036722190154:android:1711559c43a09757a973b3',
    messagingSenderId: '1036722190154',
    projectId: 'sehatgah-e3a20',
    storageBucket: 'sehatgah-e3a20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8VuSXDwZVyjGt-YO8qGFPeMBN8QxIVAs',
    appId: '1:1036722190154:ios:b145ed2cbbd2cf9ba973b3',
    messagingSenderId: '1036722190154',
    projectId: 'sehatgah-e3a20',
    storageBucket: 'sehatgah-e3a20.appspot.com',
    iosClientId: '1036722190154-2f10342m1fv3mrmjurb3e8bedmmq2vhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8VuSXDwZVyjGt-YO8qGFPeMBN8QxIVAs',
    appId: '1:1036722190154:ios:b145ed2cbbd2cf9ba973b3',
    messagingSenderId: '1036722190154',
    projectId: 'sehatgah-e3a20',
    storageBucket: 'sehatgah-e3a20.appspot.com',
    iosClientId: '1036722190154-2f10342m1fv3mrmjurb3e8bedmmq2vhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp',
  );
}
